spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/v_lineup
    username: root
    password: root
  application:
    name: home-swagger
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #下划线转驼峰命名
  type-aliases-package: com.vlineup.entity #xml实体类全包名的前缀（resultType)


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true




